### ISSUE TITLE
crossval breaks on supervised model

### ISSUE THREAD

**Issue by andrewcstewart** [pbiecek/bgmm#4]
Using the supervised example from the documentation, crossval fails with the following error:

```
> crossval(model = supervised(knowns=genotypes$knowns, 
+                     class=genotypes$labels),folds=10)
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
In addition: Warning message:
In rep(1:folds, length.out = n) :
  first element used of 'length.out' argument
```

**Comment by pbiecek** [comment]
Thanks, 
for supervised models one needs to set fun=supervised.
I've extended the list of examples in crossval.Rd
to state this requirement directly
(see the example below)

Also there was issue with empty X, but now it's fixed

set.seed(1313)
simulated = simulateData(d=2, k=3, n=300, m=60, cov="0", within="E", n.labels=2)
amodel = supervised(knowns=rbind(simulated$X, simulated$knowns), class=simulated$Ytrue)
str(crossval(model=amodel, folds=6, fun=supervised))

**Comment by andrewcstewart** [comment]
Ok, noted.   Thanks.

I am getting an error with that example though btw:

```
> set.seed(1313)
> simulated = simulateData(d=2, k=3, n=300, m=60, cov="0", within="E", n.labels=2)
> amodel = supervised(knowns=rbind(simulated$X, simulated$knowns), class=simulated$Ytrue)
> str(crossval(model=amodel, folds=6, fun=supervised))
Error in if (model.structure$mean != "D") { : argument is of length zero
In addition: Warning message:
In rep(1:folds, length.out = n) :
  first element used of 'length.out' argument
```

Also, on a semi-related note, I've been modifying the crossval function to return the predicted classes for subsequent model validation.  Any interest in a pull-request?

It's basically just adding the following (in the within-fold loop):
```
preds[names(predTmp$class.X)] <- predTmp$class.X
```

**Comment by pbiecek** [comment]
I cannot replicate this error, 
following code is working for me:

library(devtools)
install_github("pbiecek/bgmm")
library(bgmm)
 set.seed(1313)
 simulated = simulateData(d=2, k=3, n=300, m=60, cov="0", within="E", n.labels=2)
 amodel = supervised(knowns=rbind(simulated$X, simulated$knowns), class=simulated$Ytrue)
 str(crossval(model=amodel, folds=6, fun=supervised))


Fee free to submit pull-request if you find preds useful in the output of crossval
